### ISSUE TITLE
Fallback for IE <10

### ISSUE THREAD

**Issue by matbor** [dudleystorey/CSSslidy#1]
The Fallback for IE <10, anyway of just displaying the first image only? or any other single image only.

**Comment by matbor** [comment]
if you are using the forked version, https://github.com/fillswitch/CSSslidy

Then you can use the following code to make it display just the one image.
http://jsfiddle.net/fmpeyton/qW68C/

**Comment by fillippeyton** [comment]
Also, the forked version mentioned above has now been merged into the main repo: https://github.com/dudleystorey/CSSslidy
